name: Stop VM

on:
  workflow_run:
    workflows:
      - "SelfHosted"
    types:
      - completed

jobs:
  stop_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Download RUNNER from SelfHosted workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: runner
      - name: Download PR_NUMBER from SelfHosted workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: pull-request-number
      - name: Download PR_SHA from SelfHosted workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: pull-request-sha

      - name: Set runner variable from RUNNER file
        id: runner
        run: echo "::set-output name=runner::$(cat "RUNNER")"

      - name: Set pull request variable from PR_NUMBER file
        id: pull-request-number
        run: echo "::set-output name=pull-request-number::$(cat "PR_NUMBER")"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Stop VM
        run: gcloud compute instances stop --zone=europe-west1-b ${{steps.runner.outputs.runner}}

      - name: Remove runner label
        if: always()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { labels: labels } } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{steps.pull-request-number.outputs.pull-request-number}}
            })
            github.issues.removeLabel({
              issue_number: ${{steps.pull-request-number.outputs.pull-request-number}},
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['${{steps.runner.outputs.runner}}']
            })
